config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :courses do
  	member do
  		put "add", to: "courses#library"
  		put "remove", to: "courses#library"
  	end
  end

  resources :library, only:[:index]
  resources :pricing, only:[:index]
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'
  resources :subscriptions
  resources :home, only:[:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord

	has_one_attached :thumbnail
	belongs_to :user
	has_many :libraries
	has_many :added_courses, through: :libraries, source: :user

end

app/models/library.rb
class Library < ApplicationRecord

	belongs_to :course
	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :courses, dependent: :destroy
  has_many :libraries
  has_many :library_additions, through: :libraries, source: :course

  def subscribed?
  	stripe_subscription_id?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :set_course, only: [:show, :edit, :update, :destroy, :library]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = current_user.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = current_user.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Add and remove courses from/to library for current user
  def library

    type = params[:type]

    if type == "add"

      current_user.library_additions << @course
      redirect_to library_index_path, notice: "#{@course.title} was added to your library."

    elsif type == "remove"

      current_user.library_additions.delete(@course)
      redirect_to root_path, notice: "#{@course.title} was removed from your library."

    else

      # type is missing, nothing should happen
      redirect_to course_path(@course), notice: "Looks like nothing happened. Try again."
      
    end
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description, :teacher, :thumbnail, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout "home"
	

  def index

  	if user_signed_in? && current_user.subscribed?
  		redirect_to courses_path
  	end
  	
  end

end

app/controllers/library_controller.rb
class LibraryController < ApplicationController

	before_action :authenticate_user!

  def index
  	@library_courses = current_user.library_additions
  end

end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController

	layout "subscribe"

	def index
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	protected

		def after_sign_up_path_for(resource)
			'/pricing'
		end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  layout "subscribe"
  before_action :authenticate_user!, except: [:new, :create]

  def new
    if user_signed_in? && current_user.subscribed?
      redirect_to root_path, notice: "You are already a subscriber"
    end
  end

  def create
    Stripe.api_key = Rails.application.credentials.stripe_api_key

    plan_id = params[:plan_id]
    plan = Stripe::Plan.retrieve(plan_id)
    token = params[:stripeToken]

    customer = if current_user.stripe_id?
                Stripe::Customer.retrieve(current_user.stripe_id)
               else
                Stripe::Customer.create(email: current_user.email, source: token)
              end

    subscription = customer.subscriptions.create(plan: plan.id)

    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
      subscribed: true
    }

    options.merge!(
      card_last4: params[:user][:card_last4],
      card_exp_month: params[:user][:card_exp_month],
      card_exp_year: params[:user][:card_exp_year],
      card_type: params[:user][:card_type]
    ) if params[:user][:card_last4]

    current_user.update(options)

    redirect_to root_path, notice: "Your subscription was setup successfully!"
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)
    current_user.subscribed = false

    redirect_to root_path, notice: "Your subscription has been cancelled."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user_subscribed?
		user_signed_in? && current_user.subscribed?
	end

	def admin?
		user_signed_in? && current_user.admin?		
	end

	def subscribed?
		user_signed_in? && current_user.subscribed?
	end

	def titleize(str)
		str.gsub('_',' ').capitalize
	end

end

app/helpers/courses_helper.rb
module CoursesHelper

	def user_added_to_library? user, course
		user.libraries.where(user: user, book: book).any?
	end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/courses/_course-controls.html.erb
 <% if subscribed? %>

  <% if user_added_to_library?(current_user, course) %>

    <%= link_to 'Remove from library', add_course_path(course, type: "remove"), method: :put, class: "button is-danger is-fullwidth" %>

    <% if controller.controller_name == "library" %>
      <%= link_to 'Download', '#', class:"button is-success is-fullwidth mt1" %>
    <% end %>

  <% else %>
    <%= link_to 'Add to library', add_course_path(course, type: "add"), method: :put, class: "button is-link is-fullwidth" %>
  <% end %>

<% else %>
  <%= link_to 'Add to library', new_user_registration_path, class: "button is-link is-fullwidth" %>
<% end %>

app/views/courses/_course.html.erb
<div class="course">
  <div class="card">
    <div class="card-image">
      <figure class="image is-3by4">
        <%= link_to image_tag(course.thumbnail), course %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-4"><%= course.title %></p>
          <p class="subtitle is-6"><%= course.teacher %></p>
        </div>
      </div>

      <div class="content">
         <% if subscribed? %>

          <% if user_added_to_library?(current_user, course) %>

            <%= link_to 'Remove from library', add_course_path(course, type: "remove"), method: :put, class: "button is-danger is-fullwidth" %>

            <% if controller.controller_name == "library" %>
              <%= link_to 'Download', '#', class:"button is-success is-fullwidth mt1" %>
            <% end %>

          <% else %>
            <%= link_to 'Add to library', add_course_path(course, type: "add"), method: :put, class: "button is-link is-fullwidth" %>
          <% end %>

        <% else %>
          <%= link_to 'Add to library', new_user_registration_path, class: "button is-link is-fullwidth" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="controls pt2">
    <% if admin? %>
      <%= link_to 'Edit', edit_course_path(course), class:"button is-small is-rounded" %>
      <%= link_to 'Delete', course, method: :delete, data: { confirm: "Are you sure? "}, class:"button is-small is-rounded" %>
    <% end %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= simple_form_for @course, html: { multipart: true } do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="field">
    <div class="control">
      <%= f.input :title, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :description, required: true, input_html: { class: "textarea"}, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :teacher, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <div class="file">
        <label class="file-label">
          <%= f.input :thumbnail, as: :file, required: true, input_html: { class: "file-input" }, wrapper: false, label: false  %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fa fa-upload"></i>
            </span>
            <span class="file-label">
              Choose a thumbnail…
            </span>
          </span>
        </label>
      </div>
    </div>
  </div>


  <%= f.button :submit, class:"button is-dark" %>
<% end %>

app/views/courses/edit.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-6">
      <h1 class="title is-3">Editing Course</h1>
      <%= render 'form', course: @course %>
    </div>
  </div>
</section>

app/views/courses/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <i class="fa fa-video-camera"></i> Course Delivery
      </h1>
      <h2 class="subtitle">
        Check out some of the latest courses
      </h2>
    </div>
  </div>
</section>

<section class="section">
  <div class="course-grid">
    <%= render @courses %>
  </div>
</section>

app/views/courses/new.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-6">
      <h1 class="title is-3">New Course</h1>
      <%= render 'form', course: @course %>
    </div>
  </div>
</section>

app/views/courses/show.html.erb
<div class="section">
  <div class="columns">
    <div class="column is-4">
      <%= image_tag @course.thumbnail.variant(resize: "320x495"), alt: "#{@course.title} by #{@course.author}" %>
    </div>
    <div class="column">
      <h1 class="title is-2"><%= @course.title %><h1>

        <div class="content">
          <%= render 'course-controls', course: @course %>
          <p><strong>Description:</strong></p>
          <%= @course.description %>
        </div>

      <% if admin? %>
        <%= link_to 'Edit', edit_course_path(@course) %> |
      <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= yield (:body_class) %> <%= controller_name %> <%= action_name %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

     <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <div class="navbar-item">
          <h1 class="title is-5 has-text-white"><%= Rails.configuration.application_name %></h1>
        </div>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbar" class="navbar-menu">
        <div class="navba-start">
          <% if subscribed? %>
            <div class="navbar-item">
              <%= link_to library_index_path, class: 'navbar-item button is-dark' do %>
                <i class="fa fa-video-camera"></i> &nbsp;&nbsp; My Library
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if admin? %>
              <%= link_to 'New Course', new_course_path, class: 'button is-dark' %>
            <% end %>
            <div class="field is-grouped">
            <% if user_signed_in? %>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', '', class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to edit_user_registration_path, class:"navbar-item" do %>
                    <%= current_user.name %> <% if admin? %> &nbsp; <span class="tag is-warning">ADMIN</span><% end %>
                  <% end %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>
            <p class="control">
              <%= link_to "Pricing", pricing_index_path, class:"navbar-item button is-dark is-rounded" %>
            </p>
            <p class="control">
              <%= link_to "Log In", new_user_session_path, class:"navbar-item button is-dark is-rounded" %>
            </p>
            <p class="control">
              <%= link_to "Sign Up", new_user_registration_path, class:"navbar-item button is-dark is-rounded"%>
            </p>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/','data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: "stripe-key", content: Rails.application.credentials.stripe_publishable_key %>
  </head>

  <body class="<%= yield (:body_class) %> <%= controller_name %> <%= action_name %> hero is-bold is-fullheight is-primary">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <div class="navbar-item">
          <%= link_to root_path, class:"navbar-item" do %>
            <h1 class="title is-5 has-text-white"><%= Rails.configuration.application_name %></h1>
          <% end %>
        </div>
      </div>
    </nav>

    <section class="hero">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            Check our courses
          </h1>
          <h2 class="subtitle">
            <%= link_to 'Subscribe or Log In', new_user_registration_path, class:"button is-primary is-medium is-inverted is-rounded" %>
          </h2>
        </div>
      </div>
    </section>

  </body>
</html>

app/views/layouts/subscribe.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/','data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: "stripe-key", content: Rails.application.credentials.stripe_publishable_key %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <div class="navbar-item">
          <%= link_to root_path, class:"navbar-item" do %>
            <h1 class="title is-5 has-text-white"><%= Rails.configuration.application_name %></h1>
          <% end %>
        </div>
      </div>
    </nav>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/library/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <i class="fa fa-video-camera"></i> <%= current_user.name %>'s Library
      </h1>
      <h2 class="subtitle">
        Download or manage your chosen courses below
      </h2>
    </div>
  </div>
</section>

  <% if @library_courses.exists? %>
    <div class="course-grid">
      <%= render @library_courses, course: @course %>
    </div>
  <% else %>
  <article class="message">
    <div class="message-body">You haven't added any courses to your library yet. <%= link_to 'Add some', root_path %>.</div>
  </article>
  <% end %>

app/views/pricing/index.html.erb
<div class="pricing-table">

  <div class="pricing-plan is-warning">
    <div class="plan-header">Startups</div>
    <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>40</span>/month</div>
    <div class="plan-items">
      <div class="plan-item">20GB Storage</div>
      <div class="plan-item">25 Domains</div>
      <div class="plan-item">1TB Bandwidth</div>
      <div class="plan-item">-</div>
    </div>
    <div class="plan-footer">
      <% if user_signed_in? %>
        <%= link_to 'Subscribe', new_subscription_path(plan: "startups", plan_id: Rails.application.credentials.startups), class:"button is-fullwidth" %>
      <% else %>
        <%= link_to 'Subscribe', new_user_registration_path, class:"button is-fullwidth" %>
      <% end %>
    </div>
  </div>

  <div class="pricing-plan is-primary">
    <div class="plan-header">Growing Team</div>
    <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>60</span>/month</div>
    <div class="plan-items">
      <div class="plan-item">200GB Storage</div>
      <div class="plan-item">50 Domains</div>
      <div class="plan-item">1TB Bandwidth</div>
      <div class="plan-item">100 Email Boxes</div>
    </div>
    <div class="plan-footer">
      <% if user_signed_in? %>
        <%= link_to 'Subscribe', new_subscription_path(plan: "growing_team", plan_id: Rails.application.credentials.growing_team), class:"button is-fullwidth" %>
      <% else %>
        <%= link_to 'Subscribe', new_user_registration_path, class:"button is-fullwidth" %>
      <% end %>
    </div>
  </div>

  <div class="pricing-plan is-danger">
    <div class="plan-header">Enterprise</div>
    <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>100</span>/month</div>
    <div class="plan-items">
      <div class="plan-item">2TB Storage</div>
      <div class="plan-item">100 Domains</div>
      <div class="plan-item">1TB Bandwidth</div>
      <div class="plan-item">1000 Email Boxes</div>
    </div>
    <div class="plan-footer">
      <% if user_signed_in? %>
        <%= link_to 'Subscribe', new_subscription_path(plan: "enterprise", plan_id: Rails.application.credentials.enterprise), class:"button is-fullwidth" %>
      <% else %>
        <%= link_to 'Subscribe', new_user_registration_path, class:"button is-fullwidth" %>
      <% end %>
    </div>
  </div>
  
</div>

app/views/subscriptions/new.html.erb
<div class="section">
  <div class="columns is-centered">
    <div class="column is-6 border pa5">
      <h1 class="title is-3">Subscribe</h1>
      <hr />
      <p>Chosen plan: <strong><%= params[:plan] %></strong></p>
      <hr/>
      <%= form_tag subscriptions_path, id: "payment-form" do |form| %>

        <div class="field">
          <label for="card-element" class="label">Enter credit or debit card</label>

          <div id="card-element">
            <!-- A Stripe element will be intserted here !-->
          </div>

          <div id="card-errors" role="alert"></div>

          <%= hidden_field_tag :plan_id, params[:plan_id] %>

          <button class="button is-fullwidth is-link mt4">Submit</button>
        </div>

      <% end %>
    </div>
  </div>
</div>